version: "3.8"

services:
  annodomini:
    container_name: "annodomini-game"
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1 # -> only necessary if you lack a Dockerfile
    # command: sbt run # -> only necessary if you lack a dockerfile or your dockerfile doesn't implement a command
    ports:
      - "8080:8080"
    stdin_open: true

  fileio:
    container_name: "annodomini-fileio"
    build:
      context: ./fileIO
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true

    # Use root/example as user/password credentials
    version: '3.1'

    services:

      db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: example



    # mysql:
#  image: mysql:5.7
    # volumes:
    #  - annodomini-sql-database:/var/lib/mysql
    # environment:
    #  MYSQL_ROOT_PASSWORD: secret
    #  MYSQL_DATABASE: annodomini-db

